spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

JWT_SECRET: ${JWT_SECRET}
ODDS_API_KEY: ${ODDS_API_KEY}

